import * as $ from 'jquery';
import './blocks/dropdown/dropdown';
import './blocks/like-button/like-button';
import './blocks/text-field/text-field';
import './blocks/range-slider/range-slider';
import './blocks/datepicker/datepicker';
import './blocks/expandable-list/expandable-list';
import './blocks/form/form';
import './blocks/card/card';
import './blocks/room-card/room-card';
import './blocks/header/header';
import './blocks/layout/layout';
import './pages/search/search';
import './pages/room-details/room-details';

import './pages/landing/landing.pug';
import './pages/room-details/room-details.pug';
import './pages/registration/registration.pug';
import './pages/signin/signin.pug';
import './main/main.scss';
